version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./src
          target: /src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json
